name: download
description: Cross-Platform file downloader for Dart and Flutter projects.
version: 1.0.1
homepage: https://pwa.ir
repository: https://github.com/xclud/dart_download

environment:
  sdk: ">=2.12.0 <4.0.0"


dev_dependencies:
  test: ^1.25.0
  lints: ^5.1.0
